apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
  labels:
    app-type: user-application
spec:
  project: default
  source:
    repoURL: https://github.com/SumithSingh18/platform-engineering-lab
    targetRevision: main
    path: apps/hello-app
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true