apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: platform
spec:
  project: default
  source:
    repoURL: https://github.com/SumithSingh18/platform-engineering-lab
    targetRevision: main
    path: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
